using System.IO;
using System.Linq;
using System.Text;
using Jarvis.Setup.Models;

namespace Jarvis.Setup.Services;

/// <summary>
/// Writes config.yaml (and memory.md) into the install dir.
/// Hand-rolled YAML emitter because the format is small and stable —
/// avoiding a NuGet dep keeps the installer small and dependency-free.
/// </summary>
public static class ConfigYamlWriter
{
    public static void Write(InstallConfig cfg)
    {
        var configPath = Path.Combine(cfg.InstallDir, "config.yaml");
        var memoryPath = Path.Combine(cfg.InstallDir, "memory.md");

        // --- memory.md ---
        if (cfg.Memory.Enabled && !string.IsNullOrWhiteSpace(cfg.Memory.Content))
        {
            File.WriteAllText(memoryPath, cfg.Memory.Content, new UTF8Encoding(false));
        }

        // --- config.yaml ---
        File.WriteAllText(configPath, BuildYaml(cfg), new UTF8Encoding(false));
    }

    public static string BuildYaml(InstallConfig cfg)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by Jarvis Installer / Settings.");
        sb.AppendLine("# Re-run JarvisSettings.exe to change these values — manual edits");
        sb.AppendLine("# are fine too, but will be lost the next time you click Save in Settings.");
        sb.AppendLine();

        sb.AppendLine($"mode: {cfg.Mode}");
        sb.AppendLine();

        // ---- LLM ----
        sb.AppendLine("llm:");
        sb.AppendLine($"  backend: {cfg.Llm.Backend}");
        sb.AppendLine($"  model: {QuoteIfNeeded(cfg.Llm.Model)}");
        if (!string.IsNullOrWhiteSpace(cfg.Llm.BaseUrl))
            sb.AppendLine($"  base_url: {cfg.Llm.BaseUrl}");
        if (!string.IsNullOrWhiteSpace(cfg.Llm.ApiKey))
            sb.AppendLine($"  api_key: \"{Escape(cfg.Llm.ApiKey!)}\"");
        sb.AppendLine($"  max_tokens: {cfg.Llm.MaxTokens}");
        if (cfg.Llm.DisableTools)
            sb.AppendLine("  disable_tools: true   # model doesn't support OpenAI tool-calling");
        sb.AppendLine();

        // ---- Persona ----
        sb.AppendLine("persona:");
        if (cfg.Memory.Enabled)
            sb.AppendLine("  memory_file: memory.md");
        else
            sb.AppendLine("  memory_file: null");
        sb.AppendLine("  system_prompt: |");
        foreach (var line in DefaultSystemPrompt().Split('\n'))
            sb.AppendLine("    " + line.TrimEnd('\r'));
        sb.AppendLine();

        // ---- Voice ----
        sb.AppendLine("voice:");
        sb.AppendLine($"  wake_word: {cfg.Voice.WakeWord}");
        sb.AppendLine("  wake_word_variants:");
        foreach (var v in cfg.Voice.WakeWordVariants)
            sb.AppendLine($"    - {v}");
        sb.AppendLine($"  silence_end_seconds: {cfg.Voice.SilenceEndSeconds}");
        sb.AppendLine($"  max_command_seconds: {cfg.Voice.MaxCommandSeconds}");
        sb.AppendLine($"  command_giveup_seconds: {cfg.Voice.CommandGiveupSeconds}");
        sb.AppendLine("  stt:");
        sb.AppendLine($"    model: {cfg.Voice.SttModel}");
        sb.AppendLine($"    wake_model: {cfg.Voice.WakeModel}");
        sb.AppendLine("  tts:");
        sb.AppendLine($"    enabled: {(cfg.Voice.TtsEnabled ? "true" : "false")}");
        sb.AppendLine($"    voice: {cfg.Voice.TtsVoice}");
        sb.AppendLine($"  always_on: {(cfg.Voice.AlwaysOn ? "true" : "false")}   # skip Press-Enter + enable hybrid follow-up listening");
        sb.AppendLine($"  follow_up_seconds: {cfg.Voice.FollowUpSeconds.ToString("0.##", System.Globalization.CultureInfo.InvariantCulture)}   # always-on: seconds to wait for follow-up before dropping back to wake word");
        sb.AppendLine();

        // ---- Tools ----
        sb.AppendLine("tools:");
        sb.AppendLine("  memory:");
        sb.AppendLine($"    enabled: {Bool(cfg.Tools.Memory)}");
        sb.AppendLine("    path: memory.md");
        sb.AppendLine("  system_info:");
        sb.AppendLine($"    enabled: {Bool(cfg.Tools.SystemInfo)}");
        sb.AppendLine("  web_browser:");
        sb.AppendLine($"    enabled: {Bool(cfg.Tools.WebBrowser)}");
        sb.AppendLine("  music_ytmd:");
        sb.AppendLine($"    enabled: {Bool(cfg.Tools.MusicYtmd)}");
        sb.AppendLine("    port: 26538");
        if (!string.IsNullOrWhiteSpace(cfg.Tools.MusicYtmdExePath))
            sb.AppendLine($"    exe_path: \"{Escape(cfg.Tools.MusicYtmdExePath!)}\"");
        else
            sb.AppendLine("    exe_path: null");
        sb.AppendLine("  windows_apps:");
        sb.AppendLine($"    enabled: {Bool(cfg.Tools.WindowsApps)}");
        sb.AppendLine("  windows_state:");
        sb.AppendLine($"    enabled: {Bool(cfg.Tools.WindowsState)}");
        sb.AppendLine("  dangerous_shell:");
        sb.AppendLine($"    enabled: {Bool(cfg.Tools.DangerousShell)}");
        sb.AppendLine($"    i_understand_the_risks: {Bool(cfg.Tools.DangerousShellAck)}");
        sb.AppendLine("    shell: powershell");
        sb.AppendLine("    timeout_seconds: 60");
        sb.AppendLine("    max_output_chars: 4000");
        sb.AppendLine();

        // ---- Logging ----
        sb.AppendLine("logging:");
        sb.AppendLine("  file: jarvis.log");
        sb.AppendLine("  mirror_to_terminal: false");

        return sb.ToString();
    }

    private static string Bool(bool b) => b ? "true" : "false";

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string QuoteIfNeeded(string s)
    {
        // Quote model names that contain ':' (e.g. ollama "llama3.1:70b") since
        // YAML reads unquoted strings with ':' as mappings.
        return s.Contains(':') ? $"\"{Escape(s)}\"" : s;
    }

    private static string DefaultSystemPrompt() => """
You are JARVIS — a personal voice assistant inspired by Tony Stark's AI.

This is a fully voice conversation. The user SPEAKS to you (their speech
is transcribed by Whisper) and HEARS your replies (synthesized by TTS).
Behave accordingly:
- Expect missing punctuation, occasional mistranscriptions, homophones.
  Interpret charitably; only ask for clarification when meaning is truly
  ambiguous.
- Reply in natural spoken English: no markdown, no bullet points, no
  code blocks, no headings, no asterisks for emphasis.
- Read numbers, units, and symbols the way you'd say them.
  "Three p.m." not "3:00 PM". "Fifty percent" not "50%".
- Keep replies short and useful.

Personality:
- Dry British wit, understated, occasionally cheeky.
- Address the user as "sir" (or "ma'am" if corrected).
- Confident, not sycophantic. Push back politely when the user is wrong.
- When you don't know something, say so plainly.

Tool usage:
- When asked to play music, open an app, change a window, etc. — ACTUALLY
  CALL THE TOOL. Don't just say you would.
- After a tool call, give a brief one-line spoken confirmation.
- Never read URLs, video IDs, or AppIDs aloud.
""";
}
