// SPDX-License-Identifier: AGPL-3.0-or-later

// src/tools/image_generate.rs

//! `image_generate` — turn a text prompt into an image, via whichever backend
//! is configured: local Stable Diffusion (Automatic1111), local ComfyUI, OpenAI
//! Images, or an OpenAI-compatible endpoint. The tool is backend-agnostic — it
//! dispatches through [`crate::image::ImageService`].
//!
//! The generated bytes are saved to the content-addressed [`ArtifactStore`] and
//! returned as a markdown image ref (`![alt](/api/artifacts/<sha>.png)`), which
//! the chat UI already renders inline with download/copy. No extra plumbing —
//! it rides the same artifact path as `code_run`'s plots.
//!
//! Network tier; enabled when at least one image backend is configured.

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::{json, Value};
use tracing::info;

use super::{Tier, Tool, ToolArgs, ToolResult};
use crate::artifacts::ArtifactStore;
use crate::config::MiraConfig;
use crate::image::{ImageRequest, ImageService};
use crate::MiraError;

pub struct ImageGenerateTool {
    service:   Arc<ImageService>,
    artifacts: Arc<ArtifactStore>,
}

impl ImageGenerateTool {
    /// Build the tool around an [`ImageService`] router (from `[image]` +
    /// `providers.openai`) and the shared artifact store.
    pub fn new(config: &MiraConfig, artifacts: Arc<ArtifactStore>) -> Self {
        let service = Arc::new(ImageService::from_config(&config.image, &config.providers.openai));
        Self { service, artifacts }
    }

    /// Construct directly from a service (tests / alternate wiring).
    pub fn from_service(service: Arc<ImageService>, artifacts: Arc<ArtifactStore>) -> Self {
        Self { service, artifacts }
    }
}

#[async_trait]
impl Tool for ImageGenerateTool {
    fn name(&self) -> &str {
        "image_generate"
    }

    fn description(&self) -> &str {
        "Generate an ARTISTIC image from a text prompt (a generative image \
         model) and return it inline. Use for illustrations, concept art, \
         mockups, icons, and similar pictures. \
         NOT for data charts/graphs — a generative model cannot draw an \
         accurate pie/bar/line chart; for any data-driven chart or BI graph use \
         `code_run` with matplotlib instead. \
         Returns a markdown image the user sees rendered (with download/copy). \
         Not for editing an existing image. Optional `negative_prompt` (things \
         to avoid) and `backend` (openai | automatic1111 | comfyui) are honoured \
         by local Stable Diffusion / ComfyUI backends."
    }

    fn tier(&self) -> Tier {
        Tier::Network
    }

    fn enabled(&self) -> bool {
        self.service.any_enabled()
    }

    fn args_schema(&self) -> Value {
        json!({
            "type": "object",
            "required": ["prompt"],
            "properties": {
                "prompt": {
                    "type": "string",
                    "description": "Detailed description of the image to generate."
                },
                "negative_prompt": {
                    "type": "string",
                    "description": "Things to avoid in the image (used by local SD / ComfyUI backends; ignored by OpenAI)."
                },
                "model": {
                    "type": "string",
                    "description": "Backend-specific model/checkpoint (e.g. dall-e-3, gpt-image-1 for OpenAI; a checkpoint filename for local backends). Defaults to the backend's configured model."
                },
                "size": {
                    "type": "string",
                    "description": "Image dimensions as WIDTHxHEIGHT, e.g. 1024x1024 or 1024x1536. Defaults to 1024x1024."
                },
                "backend": {
                    "type": "string",
                    "description": "Which image backend to use: openai | automatic1111 | comfyui. Omit to use the configured default."
                }
            }
        })
    }

    async fn execute(&self, args: ToolArgs) -> Result<ToolResult, MiraError> {
        if !self.service.any_enabled() {
            return Ok(ToolResult::failure(
                "image_generate is unavailable — no image backend is configured. \
                 Set an OpenAI key (providers.openai.api_key), or enable a local \
                 backend under [image] (automatic1111 / comfyui).",
            ));
        }
        let Some(prompt) = args.get("prompt").and_then(Value::as_str).filter(|s| !s.trim().is_empty())
        else {
            return Ok(ToolResult::failure("image_generate: `prompt` is required."));
        };
        let backend = args.get("backend").and_then(Value::as_str);
        let (width, height) = ImageRequest::dims_from_size(
            args.get("size").and_then(Value::as_str), 1024);

        let req = ImageRequest {
            prompt:          prompt.to_string(),
            negative_prompt: args.get("negative_prompt").and_then(Value::as_str).map(str::to_string),
            model:           args.get("model").and_then(Value::as_str).map(str::to_string),
            width,
            height,
            seed:            args.get("seed").and_then(Value::as_i64),
        };

        let out = match self.service.generate(backend, &req).await {
            Ok(o)  => o,
            Err(e) => return Ok(ToolResult::failure(format!("image_generate: {e}"))),
        };

        let id = self
            .artifacts
            .save_bytes(&out.bytes, &out.ext)
            .map_err(|e| MiraError::ToolError(format!("image_generate: store artifact: {e}")))?;
        info!("image_generate: produced {} ({} bytes, backend={})",
              id.filename(), out.bytes.len(), backend.unwrap_or("default"));

        let mut md = id.markdown_image("Generated image");
        if let Some(note) = out.note {
            md.push_str(&format!("\n\n_{note}_"));
        }
        // The UI renders this image directly from the tool result. Steer the
        // model away from re-typing the link in its reply — a weak model
        // otherwise reproduces (and often mangles) the URL, yielding a
        // duplicate/broken second image. The image still shows regardless of
        // what the model says.
        md.push_str(
            "\n\n[system: the image above is already displayed to the user — do NOT repeat \
             the image link or markdown in your reply; just briefly describe it in words.]"
        );
        Ok(ToolResult::success(md))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tool(key: Option<&str>) -> ImageGenerateTool {
        let dir = tempfile::tempdir().unwrap();
        let store = Arc::new(ArtifactStore::new(dir.path()).unwrap());
        let mut cfg = MiraConfig::default();
        cfg.providers.openai.api_key = key.map(str::to_string);
        // Avoid the env var leaking into the test from the dev shell.
        unsafe { std::env::remove_var("OPENAI_API_KEY") };
        ImageGenerateTool::new(&cfg, store)
    }

    #[test]
    fn disabled_without_key_enabled_with_key() {
        assert!(!tool(None).enabled());
        assert!(tool(Some("sk-test")).enabled());
    }

    #[test]
    fn schema_requires_prompt_and_tier_is_network() {
        let t = tool(Some("sk-test"));
        assert_eq!(t.name(), "image_generate");
        assert_eq!(t.tier(), Tier::Network);
        let schema = t.args_schema();
        assert_eq!(schema["required"][0], "prompt");
        assert!(schema["properties"]["size"].is_object());
    }

    #[tokio::test]
    async fn execute_without_key_fails_gracefully() {
        let r = tool(None).execute(serde_json::json!({ "prompt": "a cat" })).await.unwrap();
        assert!(!r.success);
        assert!(r.error.unwrap().contains("no image backend is configured"));
    }

    #[tokio::test]
    async fn execute_requires_prompt() {
        let r = tool(Some("sk-test")).execute(serde_json::json!({})).await.unwrap();
        assert!(!r.success);
        assert!(r.error.unwrap().contains("prompt"));
    }
}
