# SPDX-License-Identifier: FSL-1.1-Apache-2.0
# Copyright (c) 2025 Open Computer Use Contributors
{{ if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "computer-use-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "computer-use-server.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "computer-use-server.selectorLabels" . | nindent 6 }}
{{- end }}
