#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shlex
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable, Mapping, Sequence


@dataclass(frozen=True)
class OllamaSetting:
    name: str
    value: str


@dataclass(frozen=True)
class CurrentValue:
    environment: str | None
    launchctl: str | None
    launchctl_error: str | None = None


RECOMMENDED_SETTINGS: tuple[OllamaSetting, ...] = (
    OllamaSetting("OLLAMA_CONTEXT_LENGTH", "64000"),
    OllamaSetting("OLLAMA_FLASH_ATTENTION", "1"),
    OllamaSetting("OLLAMA_KV_CACHE_TYPE", "q8_0"),
    OllamaSetting("OLLAMA_NUM_PARALLEL", "1"),
    OllamaSetting("OLLAMA_MAX_LOADED_MODELS", "1"),
)

Runner = Callable[..., subprocess.CompletedProcess[str]]


def _display_value(value: str | None) -> str:
    if value is None:
        return "unset"
    return value


def build_launchctl_commands(
    settings: Iterable[OllamaSetting] = RECOMMENDED_SETTINGS,
) -> list[list[str]]:
    return [["launchctl", "setenv", setting.name, setting.value] for setting in settings]


def format_launchctl_command(command: Sequence[str]) -> str:
    return " ".join(shlex.quote(part) for part in command)


def read_launchctl_value(
    name: str,
    runner: Runner = subprocess.run,
) -> tuple[str | None, str | None]:
    try:
        result = runner(
            ["launchctl", "getenv", name],
            capture_output=True,
            text=True,
            timeout=2,
            check=False,
        )
    except FileNotFoundError:
        return None, "launchctl not found"
    except subprocess.TimeoutExpired:
        return None, "launchctl getenv timed out"
    except OSError as exc:
        return None, str(exc)

    stdout = (result.stdout or "").strip()
    stderr = (result.stderr or "").strip()
    if result.returncode != 0:
        detail = stderr or stdout or f"exit {result.returncode}"
        return None, detail
    return stdout or None, None


def collect_current_values(
    environ: Mapping[str, str] = os.environ,
    runner: Runner = subprocess.run,
    settings: Iterable[OllamaSetting] = RECOMMENDED_SETTINGS,
) -> dict[str, CurrentValue]:
    current: dict[str, CurrentValue] = {}
    for setting in settings:
        launchctl_value, launchctl_error = read_launchctl_value(setting.name, runner=runner)
        current[setting.name] = CurrentValue(
            environment=environ.get(setting.name),
            launchctl=launchctl_value,
            launchctl_error=launchctl_error,
        )
    return current


def render_report(
    current: Mapping[str, CurrentValue],
    settings: Iterable[OllamaSetting] = RECOMMENDED_SETTINGS,
) -> str:
    lines = [
        "Jarvis Ollama long-context local setup",
        "",
        "Recommended values:",
    ]
    for setting in settings:
        values = current.get(setting.name, CurrentValue(None, None, "not checked"))
        launchctl_text = _display_value(values.launchctl)
        if values.launchctl_error:
            launchctl_text = f"{launchctl_text} ({values.launchctl_error})"
        lines.append(
            "- "
            f"{setting.name}={setting.value} "
            f"(env: {_display_value(values.environment)}, launchctl: {launchctl_text})"
        )

    lines.extend(
        [
            "",
            "Dry run: no launchctl values changed.",
            "",
            "Commands:",
            *(
                format_launchctl_command(command)
                for command in build_launchctl_commands(settings)
            ),
            "",
            "Apply with: python3 scripts/ollama_context_setup.py --apply",
            "Export with: python3 scripts/ollama_context_setup.py --export /tmp/jarvis-ollama-context.sh",
        ]
    )
    return "\n".join(lines)


def export_commands(path: Path, commands: Iterable[Sequence[str]]) -> Path:
    destination = path.expanduser().resolve()
    body = "\n".join(format_launchctl_command(command) for command in commands)
    destination.write_text(
        "#!/bin/zsh\n"
        "# Generated by scripts/ollama_context_setup.py\n"
        f"{body}\n",
        encoding="utf-8",
    )
    return destination


def apply_launchctl_settings(
    commands: Iterable[Sequence[str]],
    runner: Runner = subprocess.run,
) -> None:
    for command in commands:
        runner(list(command), check=True)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Report and optionally configure Ollama launchctl settings for Jarvis long-context local use."
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Run launchctl setenv commands. Without this flag, the helper is read-only.",
    )
    parser.add_argument(
        "--export",
        type=Path,
        help="Write the recommended launchctl commands to a zsh script instead of only printing them.",
    )
    return parser.parse_args(argv)


def main(
    argv: Sequence[str] | None = None,
    *,
    environ: Mapping[str, str] = os.environ,
    runner: Runner = subprocess.run,
) -> int:
    args = parse_args(argv)
    commands = build_launchctl_commands()
    current = collect_current_values(environ=environ, runner=runner)

    print(render_report(current))

    if args.export:
        destination = export_commands(args.export, commands)
        print()
        print(f"Exported commands to {destination}")

    if args.apply:
        apply_launchctl_settings(commands, runner=runner)
        print()
        print("Applied launchctl settings.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
